### ISSUE TITLE
"eye in speech bubble" emoji not being mapped correctly to filename

### ISSUE THREAD

**Issue by nicksellen** [jdecked/twemoji#151]
I noticed my "eye in speech bubble" emoji image was not loading - the image was not found.

The hex code for "eye in speech bubble" is `1f441-fe0f-200d-1f5e8-fe0f` but the twemoji file for that emoji is `1f441-200d-1f5e8.png`.

I see the logic in: https://github.com/jdecked/twemoji/blob/388f518b756404152f128a3539f5e7f9a6f1ebd6/scripts/build.js#L344-L350

Which is supposed to convert the emoji to the correct hexcode for the filename by sometimes removing the `fe0f` codes, but it doesn't work in this case. This is the only emoji affected.

Here's a reproducer - https://nicksellen.co.uk/upld/twemoji-issue.html - with description of the issue on the page.

Renaming the file would work, but perhaps breaks something else for someone? Or do some other logic in that function to give the correct filename without breaking the other emojis.

Given there are already lots of filenames with fe0f in (where 200d is also present) renaming the file would make sense to me!

**Comment by Shamoil009** [comment]
Having the exact same issue. And I also notice the same things. Another thing I would like to add is that the "eye in speech bubble" emoji will look correct in native and Noto Color Emoji. So problem seems to be with twemoji.

**Comment by ericali-ptc** [comment]
also met

**Comment by jdecked** [comment]
@nicksellen @Shamoil009 @ericali-ptc this should be fixed as of v17.0.3 (it was actually a parsing bug). Please have a look and confirm.

**Comment by Shamoil009** [comment]
> [@nicksellen](https://github.com/nicksellen) [@Shamoil009](https://github.com/Shamoil009) [@ericali-ptc](https://github.com/ericali-ptc) this should be fixed as of v17.0.3 (it was actually a parsing bug). Please have a look and confirm.

I checked this and I believe svg and png images are missing from assets. Now after parsing HEX code is `1f441-fe0f-200d-1f5e8-fe0f` but still not displaying correctly.

<img width="96" height="95" alt="Image" src="https://github.com/user-attachments/assets/42f16b09-78ee-425a-a87e-4f05b0b2d2b5" />\
<img width="484" height="126" alt="Image" src="https://github.com/user-attachments/assets/c1677898-35b9-4eb4-84a3-516ecce9d113" />

svg and png in assets are of this name `1f441-200d-1f5e8`.

<img width="167" height="185" alt="Image" src="https://github.com/user-attachments/assets/bc7b937d-bded-4fd6-a59b-1f50b3ace417" />

**Comment by nicksellen** [comment]
Yes, can confirm the asset is missing, I updated my reproducer to use 17.0.3 here --> https://nicksellen.co.uk/upld/twemoji-issue-17.0.3.html

There is a 404 trying to fetch https://cdn.jsdelivr.net/gh/jdecked/twemoji@17.0.3/assets/72x72/1f441-fe0f-200d-1f5e8-fe0f.png

**Comment by Shamoil009** [comment]
Just noticed now that these and many other emojis broke also in v17.0.3.

<img width="592" height="134" alt="Image" src="https://github.com/user-attachments/assets/c8a5b629-ea83-4f68-805c-5ce2b7dbcfad" />

**Comment by jdecked** [comment]
> Just noticed now that these and many other emojis broke also in v17.0.3.
> <img alt="Image" width="592" height="134" src="https://private-user-images.githubusercontent.com/77117702/618374906-c8a5b629-ea83-4f68-805c-5ce2b7dbcfad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODM0NTIwMDksIm5iZiI6MTc4MzQ1MTcwOSwicGF0aCI6Ii83NzExNzcwMi82MTgzNzQ5MDYtYzhhNWI2MjktZWE4My00ZjY4LTgwNWMtNWNlMmI3ZGJjZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzA3VDE5MTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNDNhZWM1NzI4MTgxNzBiNTBmZWRkMGJlZDgzOWU5YzAwMjlkN2QxZmU0NGRlYWI1NWI0NmE2MjYyODg3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.YaGgBL1TOZoOwu02m8qrmZVeclXy6GmmDMpjsMZcLOo">

Argh, yes, the 10 emoji tagged as `text-default,diversity` are broken:
- 1f590 (Raised hand with fingers splayed)
- 270d (Writing hand)
- 1f575 (Detective)
- 1f574 (Person in business suit levitating)
- 26f7 (Skier)
- 1f3cb (Person lifting weights)
- 26f9 (Person bouncing ball)
- 1f3cc (Person golfing)
- 270c (Victory hand)
- 261d (Up pointing index)

Will track this in https://github.com/jdecked/twemoji-parser/issues/16
